service: ai-serverless-starter-ts

provider:  
  name: aws
  runtime: nodejs4.3

plugins:  
  - serverless-webpack

functions:
  hello:
    # Should be filename.functioname
    handler: hello.hello
    events:
     - http:
         path: hello
         method: get
  hola:
    handler: hola.hola
    events:
     - http:
         path: hola
         method: get