service: ai-serverless-starter-ts

provider:  
  name: aws
  region: ap-southeast-2
  runtime: nodejs4.3
  stage  : development
  profile: development
  memorySize: 128

plugins:  
  - serverless-webpack
  - serverless-offline
  - serverless-plugin-stage-variables

custom:
  # enable auto including modules
  webpackIncludeModules: true
  packagePath: './package.json'
  webpack: ./webpack.config.js
  # stage variables available in handlers
  stageVariables:
    env : "${env:environment, self:provider.stage}"
    development:
    production:

package:
  exclude:
    - node_modules/**
    - test/**

functions:
  hello:
    # Should be filename.functioname
    handler: hello.hello
    events:
     - http:
         path: hello
         method: get
  hola:
    handler: hola.hola
    events:
     - http:
         path: hola
         method: get